version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: wolverineks-hello-world_server_1
      APP_PORT: 3000

  server:
    image: python:3-alpine
    user: "1000:1000"
    command: python /app/server.py
    volumes:
      - ${APP_DATA_DIR}/site:/app:ro
      - ${APP_DATA_DIR}/data:/data
      - ${APP_BITCOIN_DATA_DIR}:/bitcoin:ro
    environment:
      OP_RETURN_INDEX_PATH: /data/op_return_index.json
      BITCOIN_RPC_HOST: $APP_BITCOIN_NODE_IP
      BITCOIN_RPC_PORT: $APP_BITCOIN_RPC_PORT
      BITCOIN_RPC_USER: $APP_BITCOIN_RPC_USER
      BITCOIN_RPC_PASS: $APP_BITCOIN_RPC_PASS
      BITCOIN_COOKIE_FILE: /bitcoin/.cookie
    restart: on-failure
    init: true